import { Container } from 'inversify';
import { AuthController, Injector as authcontrollerınjector } from '../Controller/auth.controller';
import { BookController } from '../Controller/book.controller';
import AuthService from '../Domain/User/Auth.service';
import BookService from '../Domain/Book/Book.service';
import BookApplicationService from '../ApplicationService/BookApplicationService';
import AuthRepository from '../Domain/User/Auth.repository';
import BookRepository from '../Domain/Book/Book.repository';
import { AuthApplicationService, Injector as authApplicationInjector } from '../ApplicationService/AuthApplicationService';
import ExecutiveService from '../Domain/Executive/executive.service';
import { ExecutiveApplicationService } from '../ApplicationService/ExecutiveApplicationService';
import { ExecutiveController } from '../Controller/executive.controller';
import { MemberController } from '../Controller/Member.controller';
import { MemberApplicationService } from '../ApplicationService/MemberApplicationService';
import MemberService from '../Domain/Member/member.service';
import MemberRepository from '../Domain/Member/member.repository';
import TransactionHandler from './Transaction/TransactionManager';
import { errorHandlerMiddleware } from '../middleware/errorhandlerMiddleware';

const container = new Container();
container.bind<TransactionHandler>(TransactionHandler).toSelf();
container.bind<AuthApplicationService>(authApplicationInjector).to(AuthApplicationService).inSingletonScope();
container.bind<AuthController>(authApplicationInjector).to(AuthController).inSingletonScope();
container.bind<BookController>(BookController).toSelf();
container.bind<AuthService>(AuthService).toSelf();
container.bind<BookService>(BookService).toSelf();
container.bind<BookApplicationService>(BookApplicationService).toSelf();
container.bind<AuthRepository>(AuthRepository).toSelf();
container.bind<BookRepository>(BookRepository).toSelf();
container.bind<ExecutiveService>(ExecutiveService).toSelf();
container.bind<ExecutiveApplicationService>(ExecutiveApplicationService).toSelf();
container.bind<ExecutiveController>(ExecutiveController).toSelf();
container.bind<MemberApplicationService>(MemberApplicationService).toSelf();
container.bind<MemberController>(MemberController).toSelf();
container.bind<MemberService>(MemberService).toSelf();
container.bind<MemberRepository>(MemberRepository).toSelf();

export default container;
